### ISSUE TITLE
更新一下版本？

### ISSUE THREAD

**Issue by alex521** [Weidaicheng/jpush-api-csharp-client.Extensions#1]

**Comment by Weidaicheng** [comment]
Hi @alex521 ,

我刚刚查看了一下[Jiguang.JPush](https://www.nuget.org/packages/Jiguang.JPush/)的包版本，目前最新的是1.2.4，本来这个项目是[不计划cover小版本](https://www.nuget.org/packages/Jiguang.JPush/)的，目前JPush下载最多的版本是1.2.3，我看周末空了更新一个**1.2.3**的版本吧。
后期要找一个更简便的方法来更新啦，毕竟版本太多 我也没有实时通知🤣

**Comment by Weidaicheng** [comment]
Hi @alex521 ,

新的package已经上传。
Close this issue.
